### ISSUE TITLE
Issue with certain war audio files

### ISSUE THREAD

**Issue by saraAzari** [biltzerpos/TBB#1]
Certain war files seem to be incompatible with the software.

![erroe](https://user-images.githubusercontent.com/36019383/35656719-d5dff23c-06c6-11e8-8887-00945c36e349.jpg)

**Comment by biltzerpos** [comment]
Thanks! The error is caused when the sound files are recorded with a sample rate or bit depth not supported by the user's sound card. I have updated the code to give a better error message in that case. I will send a new version of the audio files for the Max scenario soon.
