### ISSUE TITLE
Make it more general

### ISSUE THREAD

**Issue by gauriwahi** [biltzerpos/TBB#17]
“Enter String to display” -- should be for a more general point of view so instead of using that say “Enter text to display” - this is part of the combobox when we want the user to display a string. 

##side problem for combo box
What is location tag/go to location/button location used for? (part of the combo box)

**Comment by yassinmmoussa** [comment]
On it, thanks for the feedback

**Comment by gauriwahi** [comment]
This item still needs to be resolved since it still has "Display String" as one of the options
