### ISSUE TITLE
Option Sound in Combo Box

### ISSUE THREAD

**Issue by gauriwahi** [biltzerpos/TBB#18]
When chose option sound it asks to write a file path and does not let the user browse and select the file they wish -- also not sure what sound is supposed to be used for needs to be more clear and not write Sound instead we can write something “upload audio file”

**Comment by gauriwahi** [comment]
Update: 

1. Run Authoring App
2. Click on "New Scenario"
3. Type in 1 Braille Cell, 2 buttons and name is test
4. Click on New Item
5. Select option -> Sound

Expected Behaviour: Once we click on the option sound, the user is able to browse through their existing files and select a new sound they would like to incorporate into the scenario which they are creating. 
Actual Behaviour: Asks for file path from the user, which they may not be knowledgeable of

**Comment by yassinmmoussa** [comment]
Done
