### ISSUE TITLE
Testing Scenario

### ISSUE THREAD

**Issue by gauriwahi** [biltzerpos/TBB#19]
Button location - asking for button identifier and we are not sure what the user should input. The user seems to be able to write anything and it will go through
When user clicks test scenario nothing happens (after choosing 3 options) - I'm assuming the simulator should begin

**Comment by yassinmmoussa** [comment]
1- The way the button location command is set up, it's only active after a "user input" command, it checks a boolean flag and only does what it does if the flag is set to true, and the flag is only set to true after a "user input" command.

2- Have not been able to reproduce this one.
