### ISSUE TITLE
File will not save if incorrect and does not specify what is incorrect

### ISSUE THREAD

**Issue by gauriwahi** [biltzerpos/TBB#20]
When user is saving scenario there is no feedback saying it has been saved or if they have encountered a problem. We get the option to save the scenario but it does not actually save. So when the scenario has been inputted correctly then the file saves, but otherwise if there is an issue then it acts like it is saving but doesn’t actually save the scenario and there is no feedback given explaining what went wrong. When testing creating a new scenario it only shows what we have written but does not explain if something has gone wrong. You find out that something went wrong only when you are trying to save the scenario.

**Comment by gauriwahi** [comment]
Update: The way we created the scenario is using the following steps:
1. Run Authoring App
2. Click on New Scenario
3. Enter 1 for cell, and 2 for buttons, enter name "test", click OK
4. Click on New Question
5. Type in question "Is the letter being displayed on the braille cell letter A?"
6. Braille text to be entered is "B"
7. Choose correct answer (second button for us)
8. Enter wrong message - "Sorry that is incorrect."
9. Click OK
10. Click Save and choose a place to save the file (we tried to save on our desktop)

Expected Behaviour: The scenario created has been saved to our desktop. If any of the above steps were incorrect, the user will be informed. 
Actual Behaviour: Once we click on "Save" we assumed the file would be saved to our desktop, but it was not. We were also not notified about what went wrong in the steps above.

**Comment by yassinmmoussa** [comment]
Was not able to reproduce at all
@biltzerpos 
Here is even the scenario generated on my desktop
Cell 1
Button 2
test

/~reset-buttons
Is the letter being displayed on the braille cell letter A?
/~pause:1
/~disp-string:B
/~244-start
/~skip-button:0 244-good
/~skip-button:1 244-bad
/~user-input
/~244-bad
Sorry that is incorrect.
/~skip:244-start
/~244-good

**Comment by biltzerpos** [comment]
I cannot reproduce the saving error as well.
However, there is a bug in the created scenario file. The location /~244-start is spoken by the text to speech module which is not good. Looks like the scenario is trying to jump backwards which is not really supported. Yassin, please update so that in this situation there is no start location, and we just continue with the scenario going forward.
