### ISSUE TITLE
Button Location, Go to Location, Location Tag Should be Removed (In my opinion)

### ISSUE THREAD

**Issue by gauriwahi** [biltzerpos/TBB#27]
Steps:
1. Run Authoring App
2. Click on New Scenario
3. Cell : 1, Button: 2, Title: Test 3
4. Click on New Item
5. Select option - Button Location
6. Enter "1 six"

Expected Behaviour: User is not able to enter any vague information such as steps above. The user knows what information should be selected. For example whatever existing buttons have been used already in the scenario, only those buttons should be accepted. 

Actual Behaviour: User is capable of entering any information and it will be accepted and displayed under Scenario

**Note: this scenario can also be used with Button Location. The items to be entered is very vague and the user can enter anything at this point there is no guideline as to what they should and should not enter. No error message appears either and thus when we try saving the scenario it does not

**Note 2: Another way to solve this issue is to use more general terms that the user is able to understand such as in video games we have an option "Save Progress", which is easier to understand. This feature can be implemented later on but as of now if we request someone else who is not familiar with the Authoring App they will be very confused.

**Comment by yassinmmoussa** [comment]
@biltzerpos These three options are more geared towards advanced users with more intimate knowledge of how the formatting works, I can't think of a way to make it clearer what they do exactly. I also think removing them would be a shame since they are quite useful if you have the prerequisite knowledge, but I'll take them out if you like.

**Comment by biltzerpos** [comment]
I recommend removing these features from the user interface to make things simpler, but keeping the code around in case we decide we want to reintroduce them later. Please add appropriate comments to the code to indicate that this code is for future use.

**Comment by gauriwahi** [comment]
Yes please remove these features as they are causing confusion!

**Comment by biltzerpos** [comment]
As discussed today, group all such items into an Advanced option.

**Comment by mbaljko** [comment]
when question is created, location tags are not added, etc
but location tag options are still possible via deep menu items.
low priority

**Comment by biltzerpos** [comment]
Advanced Items combobox created
