### ISSUE TITLE
Arrow Keys

### ISSUE THREAD

**Issue by gauriwahi** [biltzerpos/TBB#3]
##Description of error##
Navigation using arrow keys does not work when asked

##expected result##
Arrow keys to help with navigation when testing/creating scenario

**Comment by biltzerpos** [comment]
Hi Gauri, can you provide some more information? Is this with JAWS on Windows? Is it standard practice to navigate using just the arrow keys,  as opposed to CTRL-ALT-Arrow keys for example?

**Comment by gauriwahi** [comment]
Hi, during the testing there was a command asking the user to navigate using the arrow keys, which is in the authoring app. I don't believe it was JAWS, but it was part of the authoring app when setting up the items.
