### ISSUE TITLE
Record Audio doesn't close on cancel

### ISSUE THREAD

**Issue by gauriwahi** [biltzerpos/TBB#35]
1. Open Authoring App
2. New Scenario
3. Choose item
4. Record Audio
5. Click Record
6. Click Cancel

Expected Behaviour: When clicking cancel the box should close. 

Another thing that we did:
1. Repeat items 1-5
5. Click Cancel
6. Click Stop
7. Option still pops up to save but doesn't save

Expected behaviour: When clicking cancel the box should close, the user should not have the option to "stop recording". 
Behaviour: When clicking cancel the box does not go away

Other items to add: Pause recording. Give option for user to pause, record or delete when we stop recording.

**Comment by mbaljko** [comment]
fixed, but needs to be pushed.  will be in new release.
