### ISSUE TITLE
Need to know what is being deleted

### ISSUE THREAD

**Issue by gauriwahi** [biltzerpos/TBB#4]
##Description##
When the user is entering the text and would like to delete some part of the sentence they are not being informed of what text is being deleted. The only part they know is what is being typed in. 

##Expected Result##
User to know what characters/words have been deletd

**Comment by biltzerpos** [comment]
Interesting, I'd like to know more about the standard behaviour in this case. Maybe Runa can demonstrate how other programs behave in this regard on Wednesday?
